### ISSUE TITLE
Move scanning to voltage class

### ISSUE THREAD

**Issue by rubendegroote** [rubendegroote/CRIS-Beam-Tuning-Code#12]
The scanning methods should move to the voltage class - GUI should just signal the voltage object to do the scanning. This way it will be easier to have the optimization e.g. wait for the ramping to be finished etc.

**Comment by rubendegroote** [comment]
I have begun working on this already by moving the increase, decrease, increaseStep and decreaseStep methods to Voltage.

**Comment by rubendegroote** [comment]
Done.

**Comment by ibudincevic** [comment]
awesome
